apiVersion: apps/v1
kind: Deployment
metadata:
  name: mongo-deployment
  labels:
    app: mongodb
spec:
  replicas: 1
  selector:
    matchLabels:
      app: mongodb
      name: mongodb
  template:
    metadata:
      labels:
        app: mongodb
        name: mongodb
    spec:
      containers:
      - image: mongo
        name: mongodb
        imagePullPolicy: Always
        volumeMounts:
        - name: mongodb-data
          mountPath: /data/db
      volumes:
      - name: mongodb-data
        awsElasticBlockStore:
           volumeID: vol-00f82cea5618b1d44
           fsType: ext4
      nodeSelector: i-083c138de4a3d6a38


# db.movie.insert({"name":"Fast & Furious 1"})
# db.movie.insert({"name":"Fast & Furious 2"})
# db.movie.insert({"name":"Fast & Furious 3"})
# db.movie.insert({"name":"Fast & Furious 4"})
# db.movie.insert({"name":"Fast & Furious 5"})
# db.movie.insert({"name":"Fast & Furious 6"})

# > show dbs
# > show collections 
# > db.movie.find()
